miraklToSF = {
    #name on mirkl : name on salesforce
    "The Mushroom Light - Green Edition" : "THE MUSHROOM - GREEN",
    "50 x 50cm Outdoor Cushion, Toasted Marshmallow Scalloped Edge Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - SCALLOPED EDGE 50x50 - TOASTED MARSHMALLOW",
    "50 x 50cm Outdoor Cushion, Abstract Expressions Classic Square Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - NORMAL EDGE 50x50 - ABSTRACT EXPRESSIONS",
    "50 x 50cm Outdoor Cushion, Wildflower Bouquet Classic Square Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - NORMAL EDGE 50x50 - WILDFLOWER BOUQUET", 
    "50 x 50cm Outdoor Cushion, Olive Scalloped Edge Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - SCALLOPED EDGE 50x50 - OLIVE",
    "50 x 50cm Outdoor Cushion, Minty Geometric Classic Square Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - NORMAL EDGE 50x50 - MINTY GEOMETRIC",
    "Rechargeable LED Lantern, Portable Colour Changing Wireless Outdoor/Indoor Light, IP54, 8h" : "THE LUMA - HANDLE COLOUR - ADDITIONAL CHARGES MOQ",
    "50 x 50cm Outdoor Cushion, Sicily Seafront Classic Square Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - NORMAL EDGE 50x50 - SICILY SEAFRONT",
    "50 x 50cm Outdoor Cushion, Lavender Stripe Frill Edge Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - FRILLED EDGE 50x50 - LAVENDER STRIPE",
    "50 x 50cm Outdoor Cushion, Morning Sky Scalloped Edge Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - SCALLOPED EDGE 50x50 - MORNING SKY",
    "50 x 50cm Outdoor Cushion, Retro Green Stripe Frill Edge Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - FRILLED EDGE 50x50 - GREEN BLOCK STRIPE",
    "50 x 50cm Outdoor Cushion, Blue Colour Block Classic Square Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - NORAML EDGE 50x50 - BLUE COLOUR BLOCK",
    "3m Premium Hydraulic Garden Parasol with 45kg Wheeled Base & Cover, Grey Luxury Outdoor Umbrella" : "3m Luxury Hydraulic Parasol with 45kg Base and Cover - Grey",
    "3m Premium Hydraulic Garden Parasol with 45kg Wheeled Base & Cover, Natural Luxury Outdoor Umbrella" : "3m Luxury Hydraulic Parasol with 45kg Base and Cover - Natural",
    "The Mushroom Light - Pink Edition": "THE MUSHROOM - PINK",
    "50 x 50cm Outdoor Cushion, Shoreline Waves Classic Square Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - NORMAL EDGE 50x50 - SHORELINE WAVES",
    "Premium Heavy Duty 3x3m Pop Up Gazebo with Sides, Waterproof Garden Shelter, Steel Frame" : "Premium Pop Up Gazebo With Sides",
    "683L Premium Galvanised Steel Garden Storage Box Grey, Luxury Outdoor Cushion & Tool Storage Chest with Soft-Close Lid" : "L Premium Metal Storage Box - 683L / Green",
    "683L Premium Galvanised Steel Garden Storage Box Green, Luxury Outdoor Cushion & Equipment Storage Chest with Soft-Close Lid" : "L Premium Metal Storage Box - 683L / Green",
    "1056L Premium Galvanised Steel Garden Storage Box Green, Luxury Outdoor Cushion Storage Chest with Soft-Close Lid" : "XL Premium Metal Storage Box - 1056L / Green",
    "1056L Premium Galvanised Steel Garden Storage Box Grey, Luxury Outdoor Cushion Storage Chest with Soft-Close Lid" : "XL Premium Metal Storage Box - 1056L / Grey",
    "980L Waterproof Garden Storage Box 172 x 81.8 x 85.5cm Lockable Outdoor Cushion Storage Chest Rattan Effect Taupe" : "Heavy Duty Storage Box - 980L / Taupe",
    "980L Waterproof Garden Storage Box 172 x 81.8 x 85.5cm Lockable Outdoor Cushion Storage Chest Rattan Effect Black" : "Heavy Duty Storage Box - 980L / Black",
    "870L Waterproof Garden Storage Box 147 x 81.9 x 85.5cm Lockable Outdoor Cushion Storage Chest with Hydraulic Lid Taupe" : "Heavy Duty Storage Box - 870L / Taupe",
    "870L Waterproof Garden Storage Box 147 x 81.9 x 85.5cm Lockable Outdoor Cushion Storage Chest with Hydraulic Lid Black" : "Heavy Duty Storage Box - 870L / Black",
    "680L Waterproof Garden Storage Box 141 x 72.6 x 72.7cm Lockable Outdoor Cushion Storage Chest with Hydraulic Lid Taupe" : "Heavy Duty Storage Box - 680L / Taupe",
    "680L Waterproof Garden Storage Box 141 x 72.6 x 72.7cm Lockable Outdoor Cushion Storage Chest with Hydraulic Lid Black" : "Heavy Duty Storage Box - 680L / Black",
    "450L Waterproof Garden Storage Box 137.8 x 67.3 x 61.5cm Lockable Outdoor Cushion Storage Chest with Hydraulic Lid Taupe" : "Heavy Duty Storage Box - 450L / Taupe",
    "270L Waterproof Garden Storage Box 117 x 53.5 x 55cm Lockable Outdoor Cushion & Tool Storage Chest with Wood Effect Finish Taupe" : "Heavy Duty Storage Box - 270L / Taupe",
    "2.7m Garden Parasol with Base & Cover, Sage Green UV50 Tilt Patio Umbrella with Aluminium Pole" : "2.7M PARASOL SAGE",
    "2.7m Garden Parasol with Base & Cover, Green Stripe UV50 Tilt Patio Umbrella with Aluminium Pole" : "PARASOL WITH COVER - 2.7m FRINGED EDGE - THE STRIPE",
    "2.7m Garden Parasol with Base & Cover, Pink Floral UV50 Tilt Patio Umbrella with Aluminium Pole" : "PARASOL WITH COVER - 2.7m BEVELED EDGE - THE BLOSSOM",
    "2.7m Garden Parasol with Base & Cover, Floral UV50 Tilt Patio Umbrella with Aluminium Pole" : "PARASOL WITH COVER - 2.7m ZIG ZAG EDGE - THE BOUQUET",
    "2.7m Garden Parasol with Base & Cover, Brown Stripe Scalloped Edge UV50 Tilt Patio Umbrella with Aluminium Pole" : "PARASOL WITH COVER - 2.7m SCALLOPED EDGE - THE SCALLOP",
    "2.7m Garden Parasol with Base & Cover, Blue Wave UV50 Tilt Patio Umbrella with Aluminium Pole" : "PARASOL WITH COVER - 2.7m STANDARD EDGE - THE WAVE",
    "The Classic Garden Bistro - Sunset Red" : "THE CLASSIC BISTRO - SUNSET RED",
    "The Classic Garden Bistro - Forest Green" : "THE CLASSIC BISTRO - FOREST GREEN",
    "The Blaze Smokeless Firepit Compact 18cm Stainless Steel Wood Pellet Firepit with Carry Bag for Gardens, Patios & Camping" : "THE BLAZE FIREPIT - STEEL - 18cm",
    "The Classic Garden Bistro - Sky Blue" : "THE CLASSIC BISTRO - SKY BLUE",
    "The Blaze Smokeless Firepit - Green" : "THE BLAZE FIREPIT - GREEN - 18cm",
    "The Classic Garden Bistro - Champagne" : "THE CLASSIC BISTRO - CHAMPAGNE",
    "The Mushroom Light - Black Edition" : "THE MUSHROOM - BLACK",
    "The Classic Garden Bistro - Midnight Blue" : "THE CLASSIC BISTRO - MIDNIGHT BLUE",
    "50 x 50cm Outdoor Cushion, Spring Meadow Classic Square Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - NORMAL EDGE 50x50 - SPRING MEADOW",
    "50 x 50cm Outdoor Cushion, Summertime Snooze Classic Square Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - NORMAL EDGE 50x50 - SUMMERTIME SNOOZE",
    "50 x 50cm Outdoor Cushion, Lemon Meringue Scalloped Edge Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - SCALLOPED EDGE 50x50 - LEMON MERINGUE",
    "50 x 50cm Outdoor Cushion, Wine Red Scalloped Edge Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - SCALLOPED EDGE 50x50 - WINE RED",
    "50 x 50cm Outdoor Cushion, Parasol Party Classic Square Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - NORMAL EDGE 50x50 - PARASOL PARTY",
    "50 x 50cm Outdoor Cushion, Orange Colour Block Classic Square Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - NORMAL EDGE 50x50 - ORANGE COLOUR BLOCK",
    "50 x 50cm Outdoor Cushion, Brown Stripe Frill Edge Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - FRILLED EDGE 50x50 - BROWN BLOCK STRIPE",
    "The Classic Garden Bistro - Olive" : "THE CLASSIC BISTRO - OLIVE",
    "The Mushroom Light - Orange Edition" : "THE MUSHROOM - ORANGE",
    "50 x 50cm Outdoor Cushion, Ocean Stripes Frill Edge Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - FRILLED EDGE 50x50 - OCEAN BLUE STRIPE",
    "50 x 50cm Outdoor Cushion, Green Tartan Frill Edge Design, Shower-Resistant Square Cushion for Garden & Patio" : "CUSHION - FRILLED EDGE 50x50 - FARMHOUSE TARTAN",
}