#All weights in KG
weight = {
    "Heavy Duty Storage Box - 980L / Black":38,
    "Heavy Duty Storage Box - 870L / Black":31,
    "Heavy Duty Storage Box - 680L / Black":21,
    "Heavy Duty Storage Box - 980L / Taupe":38,
    "Heavy Duty Storage Box - 870L / Taupe":31,
    "Heavy Duty Storage Box - 680L / Taupe":21,
    "Heavy Duty Storage Box - 450L / Taupe":17,
    "Heavy Duty Storage Box - 270L / Taupe":10,
    "L Premium Metal Storage Box - 683L / Green":50,
    "XL Premium Metal Storage Box - 1056L / Green":63,
    "XL Premium Metal Storage Box - 1056L / Grey":63,
    "L Premium Metal Storage Box - 683L / Grey":50,
    "Buffalo Pro Heavy Duty Wire Rack XL1820":44,
    "Buffalo Pro Heavy Duty Wire Rack L1500":38,
    "Buffalo 5 Tier MDF Shelf - L1500":32,
    "Buffalo 5 Tier MDF Shelf - M1200":27,
    "Buffalo 5 Tier Corner MDF Shelf":29,
    "Buffalo Heavy Duty Workbench":35,
    "Buffalo 5 Shelf Metal Cabinet":40,
    "Buffalo Metal Storage Unit with wheels":49,
    "3m Luxury Hydraulic Parasol with 45kg Base and Cover - Grey":58,
    "3m Luxury Hydraulic Parasol with 45kg Base and Cover - Natural":58,
    "Premium Pop Up Gazebo With Sides":27,
}